language: php

php:
  - 7.1.19

before_script:
  - cp .env.travis .env
  - mysql -e 'create database blog;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
  
services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor
    
env:
  - TRAVIS_NODE_VERSION="4"
