runtime: php72

runtime_config:
  document_root: public


env_variables:
  APP_LOG: errorlog
  APP_KEY: base64:R0nmxIOmgTQMS27i9pIqC+v0E31bRSeziBsfr0Qeef8=base64:R0nmxIOmgTQMS27i9pIqC+v0E31bRSeziBsfr0Qeef8=

  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_DATABASE: blog
  DB_USERNAME: root
  DB_PASSWORD: password
  DB_SOCKET: "/cloudsql/capstone-project-235711:australia-southeast1:mysql-capstone"


